# Generated by Django 2.2 on 2021-10-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否上线'),
        ),
    ]
